/* Criação de tabela com chave primária e restrição de não nulos nomeadas */ 

CREATE TABLE CEP_CORREIOS (
CEP INTEGER CONSTRAINT CEP_CHAVE_PRIMARIA PRIMARY KEY CONSTRAINT CEP_OBRIGATORIO NOT NULL,
LOGRADOURO TEXT (100) CONSTRAINT LOGRADOURO_OBRIGATORIO NOT NULL,
BAIRRO TEXT (100) CONSTRAINT BAIRRO_OBRIGATORIO NOT NULL,
CIDADE TEXT (100) CONSTRAINT CIDADE_OBRIGATORIA NOT NULL,
ESTADO TEXT (100) CONSTRAINT ESTADO_OBRIGATORIO NOT NULL
);

/* Criação de tabela com chave primária gerada com auto incremento, restrição de não nulos, chaves estrangeira para a tabela anterior, restrição de domínio de valores em uma lista nomeadas */ 

CREATE TABLE ALUNO (
MATRICULA INTEGER CONSTRAINT ALUNO_CHAVE_PRIMARIA PRIMARY KEY AUTOINCREMENT CONSTRAINT MATRICULA_OBRIGATORIA NOT NULL,
NOME TEXT (100) CONSTRAINT NOME_OBRIGATORIO NOT NULL,
ENDERECO_NUMERO TEXT (15) CONSTRAINT NUMERO_ENDERECO_OBRIGATORIO NOT NULL,
ENDERECO_COMPLEMENTO TEXT (25),
ENDERECO_CEP INTEGER CONSTRAINT CEP_ENDERECO_OBRIGATORIO NOT NULL CONSTRAINT CEP_CHAVE_ESTRANGEIRA REFERENCES CEP_CORREIOS (CEP),
DATA_NASCIMENTO INTEGER CONSTRAINT DATA_NASCIMENTO_OBRIGATORIA NOT NULL,
SEXO TEXT (25) CONSTRAINT SEXO_OBRIGATORIO NOT NULL CONSTRAINT SEXO_INVALIDO CHECK (SEXO IN ('Feminino', 'Masculino', 'Prefiro não informar') ),
E_MAIL TEXT (100) CONSTRAINT E_MAIL_OBRIGATORIO NOT NULL CONSTRAINT E_MAIL_UNICO UNIQUE
);

/* Criação de tabela com chave primária, restrição de não nulos, restrição de domínio de valores em um intervalo nomeadas */ 

CREATE TABLE CURSO (
CODIGO INTEGER CONSTRAINT CURSO_CHAVE_PRIMARIA PRIMARY KEY NOT NULL,
NOME TEXT (100) CONSTRAINT NOME_OBRIGATORIO NOT NULL,
OBJETIVO TEXT (500) CONSTRAINT OBJETIVO_OBRIGATORIO NOT NULL,
EMENTA TEXT (500) CONSTRAINT EMENTA_OBRIGATORIA NOT NULL,
IDIOMA TEXT (25) CONSTRAINT IDIOMA_OBRIGATORIO NOT NULL,
CATEGORIA TEXT (25) CONSTRAINT CATEGORIA_OBRIGATORIA NOT NULL,
CARGA_HORARIA INTEGER CONSTRAINT CARGA_HORARIA_OBRIGATORIA NOT NULL CONSTRAINT CHECK_CARGA_HORARIA CHECK (CARGA_HORARIA >= 4 AND CARGA_HORARIA <= 80),
DATA_INICIO_INSCRICAO INTEGER,
DATA_FINAL_INSCRICAO INTEGER
);

/* Criação de tabela com chave primária com duas colunas, restrição de não nulos, chave estrangeira nomeadas */ 

CREATE TABLE Palavra_Chave_Curso (
CODIGO INTEGER CONSTRAINT PALAVRA_CHAVE_CURSO_CHAVE_ESTRANGEIRA REFERENCES CURSO (CODIGO) CONSTRAINT CODIGO_CURSO_OBRIGATORIO NOT NULL,
PALAVRA_CHAVE TEXT (25) CONSTRAINT PALAVRA_CHAVE_OBRIGATORIA NOT NULL,
CONSTRAINT PALAVRA_CURSO_CHAVE_PRIMARIA PRIMARY KEY (CODIGO, PALAVRA_CHAVE)
);

/* Criação de tabela com chave primária com duas colunas, restrição de não nulos, chave estrangeira nomeadas */ 

CREATE TABLE Inscrito_Em (
MATRICULA INTEGER CONSTRAINT ALUNO_INSCRITO_EM_CHAVE_ESTRANGEIRA REFERENCES ALUNO (MATRICULA) CONSTRAINT MATRICULA_INSCRITA_EM_OBRIGATORIA NOT NULL,
CODIGO INTEGER CONSTRAINT CODIGO_INSCRITO_EM_OBRIGATORIO NOT NULL CONSTRAINT CURSO_INSCRITO_EM_CHAVE_ESTRANGEIRA REFERENCES CURSO (CODIGO),
DATA_INSCRICAO INTEGER CONSTRAINT DATA_INSCRICAO_OBRIGATORIA NOT NULL,
PERCENTUAL_PROGRESSO  NUMERIC,
NOTA_FINAL            INTEGER,
DATA_ULTIMA_ATIVIDADE INTEGER,
CONSTRAINT INSCRITO_EM_CHAVE_PRIMARIA PRIMARY KEY (MATRICULA, CODIGO)
);

/* Alteração de tabela para incluir coluna com restrição de não nulos */ 

ALTER TABLE CEP_CORREIOS 
ADD COLUMN UF TEXT(2) CONSTRAINT UF_OBRIGATORIO NOT NULL;

/* Alteração de tabela para excluir coluna */ 

ALTER TABLE CEP_CORREIOS DROP COLUMN ESTADO;